test backend EC2 failing to connect, test smoke-test job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -623,8 +623,17 @@ jobs:
       - run:
           name: Frontend smoke test.
           command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-west-2.amazonaws.com"
-            curl -s ${URL} | grep "Welcome"
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+                # Change this to 0 after the job fails
+              echo "frontend smoke test success"
+              exit 0
+            else
+              echo "frontend smoke test failed"
+              exit 1
+            fi
 
       #- destroy-environment:
           #workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
@@ -690,8 +699,10 @@ jobs:
             if curl -s ${URL} | grep "Welcome"
             then
                 # Change this to 0 after the job fails
+              echo "frontend smoke test success"
               exit 0
             else
+              echo "frontend smoke test failed"
               exit 1
             fi
       # Here's where you will add some code to rollback on failure  
