update the run-migrations job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -216,14 +216,29 @@ jobs:
       - run:
           name: Run migrations
           command: |
-            # Your code here
-            exit 1
+            # Your code 
+
+            cd backend
+            npm install
+            # Run and save the migration output
+
+            npm run migrations > migrations_dump.txt
       - run:
           name: Send migration results to memstash
           command: |
             # Your code here
-            exit 1
-     # Here's where you will add some code to rollback on failure      
+
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+            then
+              
+                # If you are using kvdb.io, generate the bucket ID "9GE4jRtKznmVKRfvdBABBe" in your local terminal first
+                curl https://kvdb.io/CABr8rm7FqeskeNbCghtvC/cicd-db-migration_$\{CIRCLE_WORKFLOW_ID:0:7\}  -d '1'
+            
+            fi
+
+            #exit 1
+     # Here's where you will add some code to rollback on failure
+      - destroy-environment
 
   deploy-frontend:
     docker:
