test backend EC2 failing to connect, test smoke-test job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -58,14 +58,17 @@ commands:
           when: on_fail # Add when this will run
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS=$(curl --insecure  https://kvdb.io/CABr8rm7FqeskeNbCghtvC/cicd-db-migration-<< parameters.workflow_id >>)
-            if (( $SUCCESS==1 )); 
+            SUCCESS=$(curl --insecure  https://kvdb.io/${KVDB_BUCKET}/cicd-db-migration-<< parameters.workflow_id >>)
+            if (( $SUCCESS == 1 )); 
             then
                 cd ~/project/backend
                 npm install
-            #  Add revert code here. You can find this in the Getting Started section.
+                #  Add revert code here. You can find this in the Getting Started section.
                 npm run migration:revert
-            #exit 1
+                #exit 1
+                echo "revert migrations succeed"
+            else
+              echo "revert migrations failed"
             fi
 
   slacknotify:
@@ -339,11 +342,7 @@ jobs:
             # Your code 
 
             cd backend
-            npm i
-            npm run build
-            
-            # Run and save the migration output
-
+            npm install
             npm run migrations > migrations_dump.txt
             cat migrations_dump.txt
             
@@ -355,11 +354,11 @@ jobs:
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
               
-                curl https://kvdb.io/CABr8rm7FqeskeNbCghtvC/cicd-db-migration-$\{CIRCLE_WORKFLOW_ID:0:7\}  -d '1'
+                curl https://kvdb.io/${KVDB_BUCKET}/cicd-db-migration-$\{CIRCLE_WORKFLOW_ID:0:7\}  -d '1'
 
                 echo "DB migration executed successfully"
             else
-                echo "DB migration has been failed"
+                echo "No migrations are pending"
             fi
 
             #exit 1
@@ -440,13 +439,15 @@ jobs:
       - image: python:3.7-alpine3.11
     steps:
       - checkout
+      - restore_cache:
+          keys: [backend-build]
+
       - add_ssh_keys:
           fingerprints: 
             - "21:5f:82:3c:6b:f7:53:e5:f9:75:8c:96:a3:54:ec:06"
       - attach_workspace:
           at: ~/
-      - restore_cache:
-          keys: [backend-build]
+      
       - run:
           name: Install dependencies
           command: |
@@ -455,15 +456,34 @@ jobs:
             apk add --no-cache openssh-client
             apk add --no-cache --upgrade bash
             pip install awscli
-      - create-dotenv-file
+      #- create-dotenv-file
       - run:
-          name: Deploy backend
-          command: |
-            pwd
-            tar czf backend.tar.gz backend/
-            export ANSIBLE_HOST_KEY_CHECKING=false
-            #ansible-playbook -i ./.circleci/ansible/inventory.txt ./.circleci/ansible/deploy-backend.yml -vvv
-            ansible-playbook -i .circleci/ansible/inventory.txt .circleci/ansible/deploy-backend.yml -vvv
+        name: Install dependencies
+        command: |
+          cd backend
+          npm install
+
+      - run:
+        name: Package Backend
+        command: |
+          cd backend
+          npm run build
+          tar -czf artifact.tar.gz dist/* package*
+
+          cd ..
+          cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
+
+      - run:
+        name: Deploy backend
+        command: |
+          export TYPEORM_MIGRATIONS_DIR=./migrations
+          export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
+          export TYPEORM_MIGRATIONS=./migrations/*.ts
+
+          cd .circleci/ansible
+          cat inventory.txt
+          ansible-playbook -i inventory.txt deploy-backend.yml
+
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
       - revert-migrations:
